### ISSUE TITLE
angularjs-multiselect-dropdown-makes-page-heavy-due-to-documents-click-event

### ISSUE THREAD

**Issue by alpeshkumarpr** [dotansimha/angularjs-dropdown-multiselect#134]
Hello, I have posted one issue related to droddown closing event on github.

http://stackoverflow.com/questions/31891118/angularjs-multiselect-dropdown-makes-page-heavy-due-to-documents-click-event

I have also found that AngularJS keeps watching your DOM and thus slows down application's performance.

What can be done as an alternative ?

Thanks.

**Comment by odedfos** [comment]
I've added an optimization to the template generation so that the dropdown is lazy-generated, reducing the number of watches significantly.
This should speed up your page loading and behavior on clicks events.

I submitted a pull-request, but the repository doesn't seem to be frequently maintained.
You can check-out from here: https://github.com/odedfos/angularjs-dropdown-multiselect

**Comment by acedward** [comment]
Works great for big/many drop-downs

**Comment by pkempenaers** [comment]
This pull request has been merged into my fork (which i'm actively maintaining).

You can find the fork [here](https://github.com/myforce/angularjs-dropdown-multiselect)
and documentation [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

Feel free to create issues in that repository.
