### ISSUE TITLE
feature request: filterSearch by field name

### ISSUE THREAD

**Issue by racabe** [dotansimha/angularjs-dropdown-multiselect#235]
Hi, I needed, if it is possible, that you add the posibility to filter by a field name. I tried to modify your code and I add a new attribute. You can see the follow code :

[angularjs-dropdown-multiselect_new.txt](https://github.com/dotansimha/angularjs-dropdown-multiselect/files/250282/angularjs-dropdown-multiselect_new.txt)

If you think that all is correct, I would like that you add this new feature.

Thanks for all and sorry for my english.

**Comment by pkempenaers** [comment]
Hi,

I've implemented  something like this at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

**Difference with your implementation**
Instead of specifying the searchField as an attribute, you have to specify it as a setting in the settings object.

This is included from version 1.4.0.
Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

**Comment by racabe** [comment]
Ok. It  is by the same way more or less. So, I will use yours because you are actively maintaining it.

Thanks for all.

**Comment by pkempenaers** [comment]
You can now change back to this repo :)
