### ISSUE TITLE
Is there any way to have fixed number of unselected option?

### ISSUE THREAD

**Issue by DeySuparna** [dotansimha/angularjs-dropdown-multiselect#242]

**Comment by Ashviniv** [comment]
There is no way available to have fixed number of unselected option currently. But if you need to limit selection you can use `selectionLimit` property by changing the number to `dropdown_items_size - unselected limit`.
If I am not wrong, It will be complicated to implement because, If I keep 2 as fixed unselected count and I have 5 items in the dropdown list. If a user selects one item which items to be kept as unselected?

**Comment by pkempenaers** [comment]
@DeySuparna do you need something like minSelectionLimit? Because otherwise ashviniv is correct.
