### ISSUE TITLE
Change the order of group by?

### ISSUE THREAD

**Issue by kamalfn** [dotansimha/angularjs-dropdown-multiselect#245]
Is there are way to control or change the order the groups are displayed when using group-by and groupByTextProvider. Its working great for but we just want the groups in the opposite order.

**Comment by oblodgett** [comment]
Having the same issue. Would like to switch the two groups around. In our case maybe a "reverse group order"?

**Comment by oblodgett** [comment]
Possible word around. So you can give the groups a different groupValue so for instance:

<div ng-dropdown-multiselect="" options="example11data" selected-model="example11model" extra-settings="example11settings" group-by="gender"></div>

// JavaScript $scope.example11model = []; $scope.example11data = [ {id: 1, label: "David", gender: 'M'}, {id: 2, label: "Jhon", gender: 'M'}, {id: 3, label: "Lisa", gender: 'F'}, {id: 4, label: "Nicole", gender: 'F'}, {id: 5, label: "Danny", gender: 'M'}]; $scope.example11settings = { groupByTextProvider: function(groupValue) { if (groupValue === 'M') { return 'Male'; } else { return 'Female'; } } };

Instead of gender being "M" and "F" make it "1" and "2" and if the groupValue is 1 or 2 print the correct "Display Value" the order is by the groupValue and not the display value. So if the groupValue doesn't matter, you can arbitrarily put in values that will order correctly. In the above example male being 1 and female being 2 the list is ordered the other direction.

**Comment by kamalfn** [comment]
Yes, I used this workaround of giving groupValues that sorted correctly for me.
