### ISSUE TITLE
Extra settings not working

### ISSUE THREAD

**Issue by chensMMG** [dotansimha/angularjs-dropdown-multiselect#289]
I'm using angular version 1.5.0 and Bootstrap version 3.3.6.
I have downloaded the project and included the 'angularjs-dropdown-multiselect.js' file in my index file,
in the controller page i have added angularjs-dropdown-multiselect dependency:

var newCampaginCtrl = angular.module('newCampaginCtrl',['angularjs-dropdown-multiselect']);

In my controller i have directive with separate scope that load in his view the dropdown, everything is working fine beside the settings. My code look like this:

HTML:
`<div ng-dropdown-multiselect="" options="drp_options" selected-model="drp_model" extra-settings="drp_settings"></div>`

JS:
`scope.drp_options = [{'label': 'option1', 'id': 'val1'}, {'label': 'option2', 'id': 'val2'}, {'label': 'option3', 'id': 'val3'}, {'label': 'option4', 'id': 'val4'}];
scope.drp_model = [];
scope.drp_settings = {
	scrollable: true,
	scrollableHeight: '50px',
	enableSearch: true,
	smartButtonMaxItems: 3
}`

I can see all of my options and select them but none of the settings is working. Why?

**Comment by pkempenaers** [comment]
Could you recreate this issue on plunkr? So that I can take a better look at what is going wrong. Thanks

**Comment by chensMMG** [comment]
This is a plunker that simulates my case as simple as i could:

http://plnkr.co/edit/ET8haJoFJEXKKME3T4be?p=preview

**Comment by pkempenaers** [comment]
At this moment the extra-settings are only applied in the link function of the component (this is bad and I know it, but a rewrite is needed for that to change) and as the link function of the component gets executed before the link function of your directive $scope.dr_settings is undefined.

A "workaround/fix" is to set $scope.dr_settings in the controller function of your directive instead of in the link function.

In general it's bad practice to use the link function for non DOM operations (again this component doesn't follow that but as said a rewrite is needed to fix that).

I've created an issue for the rewrite #290.
