### ISSUE TITLE
TypeError: collection.some is not a function

### ISSUE THREAD

**Issue by hansiemithun** [dotansimha/angularjs-dropdown-multiselect#314]
http://stackoverflow.com/questions/42758383/typeerror-collection-some-is-not-a-function-multiselect.

Please help me with the same for code changes and fixes

**Comment by pkempenaers** [comment]
have you set the selected-model ?

**Comment by hansiemithun** [comment]
yes, facing errors in integrating with plnkr with this link: https://plnkr.co/edit/TpVrc4vvXLaNHQzJ3krI?p=preview. Please have a look, probably you will understand with what i am trying to achieve

**Comment by pkempenaers** [comment]
The errors are clearly in your configuration, even your ng-if is incorrect.

I've fixed it in [this plnkr](https://plnkr.co/edit/bLx9E1EHcV6LE8zsF04D?p=preview)

What I've done to fix it:
 - ng-if changed .isUnique === 'false'/'true' to !.isUnique and isUnique
 - added attributes to $scope.entity so that for each multiselect there was an array
 - you were using an old version that still needed lodash -> I've updated the version, but could as well have included lodash.

As a general advice instead of starting with a complex implementation of something, start with a bare minimum example and get that working and build on that.
