### ISSUE TITLE
Problems with beta.3

### ISSUE THREAD

**Issue by JuliaNsk** [dotansimha/angularjs-dropdown-multiselect#322]
What was changed in beta.2 and beta 3. ?  I now get errors with digest, and have bloblems with sorting in selected list

**Comment by pkempenaers** [comment]
problem has to do with changing width of the dropdown, if you give the component a fixed width the problems should be resolved. I currently need to focus on other things than dynamic width.

**Comment by JuliaNsk** [comment]
I don't understand how width can cause Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! 
And when I check item it doesnt show in dropdown. Some format of data maybe was changed, but I cant recognise what format.

**Comment by pkempenaers** [comment]
The only thing that has been changed is in the smartbuttontext converter. Where when the button is smaller than ... only ... is displayed, however due to css displaying ... can result in the button growing => there is enough place to display "D..." => button growing, etc.
Due to smartbuttontext changing every time it's called you can get the digest error.

**Comment by JuliaNsk** [comment]
Anything helps me with this bug, but another problem is with sort
https://plnkr.co/edit/OI7UXW08lfN8CYm4y2r5?p=preview
I have list of names. When I select e.g. Sergey and Dmitriy, Sergey is upper, but when Sergey, Dmitriy and Aleksandr -> then Dmitriy is upper. Smth wrong happens with sorting
